### PR TITLE
Added support for once event listener

### PR DESCRIPTION
**Pull request by shaheenp**

### CODE REVIEW

**Comment by williamboman** [comment]
```patch
From d5a4bd2379c28bbf0350f90d8a4c276cd563407d Mon Sep 17 00:00:00 2001
From: William Boman <william@redwill.se>
Date: Sun, 22 Nov 2015 22:40:57 +0100
Subject: [PATCH] microm.js: extend EventEmitter

---
 microm.js | 27 ++++-----------------------
 1 file changed, 4 insertions(+), 23 deletions(-)

diff --git a/microm.js b/microm.js
index 8c875b9..5f457df 100644
--- a/microm.js
+++ b/microm.js
@@ -1,3 +1,4 @@
+var EventEmitter = require('events').EventEmitter;
 var adapter = require("./bower_components/webrtc-adapter/adapter.js");
 var RecordRTC = require("./bower_components/recordrtc/RecordRTC.js");
 var Promise = require('rsvp').Promise;
@@ -7,13 +8,13 @@ var config = require('./lib/config');
 
 config.setup();
 
-class Microm {
+class Microm extends EventEmitter {
   constructor() {
+    super();
     this.isRecording = false;
     this.recordRTC = null;
     this.player = null;
     this.mp3 = null;
-    this.eventListeners = {};
     this.converter = new Converter();
   }
 
@@ -190,26 +191,6 @@ class Microm {
     // TODO: Handle recording error
   }
 
-  /**
-   * Attach an event handler function for event name
-   * @param  {String} eventName 
-   * @param  {Function} handler   
-   * @return {void} 
-   */
-  on(eventName, handler) {
-    // TODO: trow error if type of handler is not a function
-    this.eventListeners[eventName] = handler;
-  }
-
-  /**
-   * Remove an event handler
-   * @param  {String} eventName 
-   * @return {void}           
-   */
-  off(eventName) {
-    //TODO: Warn if there's not eventName attached
-    delete this.eventListeners[eventName];
-  }
 }
 
-module.exports = Microm;
\ No newline at end of file
+module.exports = Microm;
-- 
2.6.3


```

**Comment by zzarcon** [comment]
@williamboman i didn't get what you want to do with **EventEmitter** it's this an Browser Api or npm module? thanks!!

**Comment by shaheenp** [comment]
@zzarcon It's a [native node module](https://github.com/nodejs/node/blob/master/lib/events.js) that can be required since you are using webpack and used in the browser.

**Comment by zzarcon** [comment]
@shaheenp I like your proposal of `once`, good job!

But I see a problem, check this use case:

```javascript
var microm = new Microm();

microm.on('timeupdate', updateTime);
microm.once('timeupdate', sendEventToGoogleAnalytics);
```

With your implementation, when we attach a `once` handler, we are overriding the `on` one... Which I think that should be compatible. What do you think? it makes sense for you?

**Comment by zzarcon** [comment]
@williamboman can you open a PR with the **EventEmitter** proposal? :)

**Comment by williamboman** [comment]
@zzarcon Done, #12.

**Comment by zzarcon** [comment]
@williamboman thanks dude, gonna take a look now

**Pull request closed without merging**
