### PR TITLE
Fixed slow splice array function in converter (replaced on slice)

### PR DESCRIPTION
**Pull request by dmdark**
Splice if very slow on large buffer size + rebuild

### CODE REVIEW

**Comment by dmdark** [comment]
Performance metrics in Chrome. Same ~20seconds record from mic.

**Splice** (50 seconds of encodeSamplesToMp3. Splice is 80% of function work):
splice


**Slice** (6 seconds of encodeSamplesToMp3)
slice

**Comment by dmdark** [comment]
@zzarcon

**Comment by zzarcon** [comment]
Hi @dmdark ! thanks for the contribution. Couldn't review this earlier, sorry about.

Would you like to become a maintainer of the repo? I can give you commit access if you are interested. I haven't made any changes on the codebase in a long time, but Im more than happy to get improvements and fixes on it! Think about it :)

**Comment by dmdark** [comment]
@zzarcon Thanks for your offer. Well, don't think library needs a lot of changes, but I can watch PR (if any) and put some fixes in it (if any other found). Will be careful :)

**Comment by zzarcon** [comment]
@dmdark you are a member now 💃

**Comment by dmdark** [comment]
@zzarcon "Only those with write access to this repository can merge pull requests. ".  ¯\_(ツ)_/¯

**Pull request merged**
